version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    groups:
      frontend:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'gradle'
    directory: '/backend'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    groups:
      backend:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
