spring:
  datasource:
    url: jdbc:mariadb://localhost:3309/learnup_backend
    username: backend
    password: backend
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only
      file: backend/docker-compose.yml
      enabled: true
