spring:
  datasource:
    url: jdbc:postgres://localhost:5517/learnup_backend
    username: backend
    password: backend
  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:db/seeds/user.sql'
  docker:
    compose:
      lifecycle-management: start_only
      file: backend/docker-compose.yml
      enabled: true

learnup:
  jwt:
    key: f87f3c8cf30f902a5f906207108ba512b7ce51e53a098701700617ce47ddb06b
