spring:
  sql:
    init:
      mode: always
  jooq:
    sql-dialect: postgres
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

learnup:
  jwt:
    expiration-in-hours: 5

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  api-docs:
    path: "/openapi/v3/api-docs"
  swagger-ui:
    url: "../openapi/v3/api-docs" # url is relative to /swagger-ui/index.html so it also works with the /api prefix
