spring:
  datasource:
    url: jdbc:postgres://localhost:5517/learntrack_backend
    username: backend
    password: backend
  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:db/seeds/user.sql'
  docker:
    compose:
      lifecycle-management: start_only
      file: backend/docker-compose.yml
      enabled: true
  mail:
    host: localhost
    port: 1030

springdoc:
  api-docs:
    path: "/openapi/v3/api-docs"
  swagger-ui:
    url: "../openapi/v3/api-docs" # url is relative to /swagger-ui/index.html so it also works with the /api prefix

learntrack:
  jwt:
    key: f87f3c8cf30f902a5f906207108ba512b7ce51e53a098701700617ce47ddb06b
  backoffice:
    username: james-kirk
    password: NCC-1701
  mailService:
    senderMailAddress: support-local@learntrack.ch
    senderName: LearnTrack Support Local
