spring:
  sql:
    init:
      mode: always
  jooq:
    sql-dialect: postgres

learntrack:
  jwt:
    expiration-in-hours: 5

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "health,info"
